In [1]:
import pandas as pd
import polars as pl 

# pc crashed when i tried to load file as json lmao so converted to parquet for optimization
#(
#    pl.scan_ndjson('season_10_20260427_070645.jsonl', infer_schema_length=None)
#    .sink_parquet('matches.parquet')
#)

all_matches = pd.read_parquet('matches.parquet')
all_matches

,id,tag,vod,date,rank,seed,type,result,season,changes,...,category,gameMode,seedType,botSource,forfeited,timelines,spectators,bastionType,completions,replayExist
0,4547059,None,[],1767312129,"{'season': None, 'allTime': None}","{'id': 'm722zpkl38bj3jud', 'nether': 'BRIDGE',...",1,"{'time': 2078680, 'uuid': '33d7e36107f24d93948...",10,[],...,ANY,default,VILLAGE,NaN,False,"[{'data': None, 'time': 2068729, 'type': 'proj...",[],BRIDGE,"[{'time': 2078680, 'uuid': '33d7e36107f24d9394...",False
1,4547060,None,[],1767312132,"{'season': None, 'allTime': None}","{'id': 'm7230lzcl6dx3o2e', 'nether': 'TREASURE...",1,"{'time': 1106445, 'uuid': 'b0604589651f4c44aad...",10,[],...,ANY,default,VILLAGE,NaN,True,"[{'data': None, 'time': 863557, 'type': 'proje...",[],TREASURE,[],False
2,4547061,None,[],1767312132,"{'season': None, 'allTime': None}","{'id': 'm723dwly8r469sq9', 'nether': 'BRIDGE',...",1,"{'time': 528242, 'uuid': '90bd9fa7c7af4299955c...",10,[],...,ANY,default,VILLAGE,NaN,True,"[{'data': None, 'time': 528241, 'type': 'proje...",[],BRIDGE,[],False
3,4547062,None,[],1767312138,"{'season': None, 'allTime': None}","{'id': 'mamhnjc5ohh06vuf', 'nether': 'TREASURE...",3,"{'time': 6033, 'uuid': None}",10,[],...,ANY,default,BURIED_TREASURE,NaN,True,"[{'data': None, 'time': 6033, 'type': 'project...",[],TREASURE,[],False
4,4547063,None,[],1767312145,"{'season': None, 'allTime': None}","{'id': 'm722vqw0qwavea3y', 'nether': 'STABLES'...",1,"{'time': 999904, 'uuid': '4001d2512e3a4f52a7e4...",10,[],...,ANY,default,SHIPWRECK,NaN,True,"[{'data': None, 'time': 999903, 'type': 'proje...",[],STABLES,[],False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5049594,9600365,None,[],1777273490,"{'season': None, 'allTime': None}","{'id': 'm722t6f9bmuhh987', 'nether': 'BRIDGE',...",2,"{'time': 588002, 'uuid': '973080614b054d7a9690...",10,"[{'uuid': '973080614b054d7a9690fd83f505f0dd', ...",...,ANY,default,RUINED_PORTAL,NaN,True,"[{'data': None, 'time': 588002, 'type': 'proje...",[],BRIDGE,[],True
5049595,9600366,None,[],1777273490,"{'season': None, 'allTime': None}","{'id': 'm7235oyqp5kt31sg', 'nether': 'TREASURE...",2,"{'time': 336868, 'uuid': '32971d61ee7146fcb738...",10,"[{'uuid': '32971d61ee7146fcb7385afe09eff042', ...",...,ANY,default,DESERT_TEMPLE,NaN,True,"[{'data': None, 'time': 336867, 'type': 'proje...",[],TREASURE,[],True
5049596,9600367,None,[],1777273491,"{'season': None, 'allTime': None}","{'id': 'm722uu70d4h4jn6o', 'nether': 'STABLES'...",2,"{'time': 1451288, 'uuid': 'd934441161df475aa20...",10,"[{'uuid': 'd934441161df475aa20fc34eb1b2c1fc', ...",...,ANY,default,VILLAGE,NaN,False,"[{'data': None, 'time': 1441280, 'type': 'proj...",[],STABLES,"[{'time': 1451288, 'uuid': 'd934441161df475aa2...",True
5049597,9600368,None,[{'url': 'https://www.twitch.tv/videos/2758137...,1777273497,"{'season': None, 'allTime': None}","{'id': 'm722y3jjr6q407k4', 'nether': 'STABLES'...",2,"{'time': 730821, 'uuid': 'c6f20e05d06d4f698cfb...",10,"[{'uuid': 'c6f20e05d06d4f698cfba361636a7024', ...",...,ANY,default,VILLAGE,NaN,False,"[{'data': None, 'time': 720732, 'type': 'proje...",[],STABLES,"[{'time': 730821, 'uuid': 'c6f20e05d06d4f698cf...",False
5049598,9600369,None,[],1777273499,"{'season': None, 'allTime': None}","{'id': 'm722yg7k6zonvv6j', 'nether': 'BRIDGE',...",2,"{'time': 1564058, 'uuid': '2e7e7d33a1ff43ed941...",10,"[{'uuid': '2e7e7d33a1ff43ed9413a0ccd9305e2c', ...",...,ANY,default,VILLAGE,NaN,False,"[{'data': None, 'time': 1554058, 'type': 'proj...",[],BRIDGE,"[{'time': 1564058, 'uuid': '2e7e7d33a1ff43ed94...",False

In [17]:
print(all_matches.columns)

Index(['id', 'tag', 'vod', 'date', 'rank', 'seed', 'type', 'result', 'season',
       'changes', 'decayed', 'players', 'beginner', 'category', 'gameMode',
       'seedType', 'botSource', 'forfeited', 'timelines', 'spectators',
       'bastionType', 'completions', 'replayExist'],
      dtype='object')

In [11]:
# getting all ranked matches
ranked_matches = all_matches[all_matches['type'].isin([2])]
ranked_matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996368 entries, 40 to 5049598
Data columns (total 23 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   tag          object
 2   vod          object
 3   date         int64
 4   rank         object
 5   seed         object
 6   type         int64
 7   result       object
 8   season       int64
 9   changes      object
 10  decayed      bool
 11  players      object
 12  beginner     bool
 13  category     object
 14  gameMode     object
 15  seedType     object
 16  botSource    float64
 17  forfeited    bool
 18  timelines    object
 19  spectators   object
 20  bastionType  object
 21  completions  object
 22  replayExist  bool
dtypes: bool(4), float64(1), int64(4), object(14)
memory usage: 468.6+ MB

In [31]:
# removing games that were created for decay
ranked_matches = ranked_matches[~ranked_matches['decayed']]

# dropping unneccessary columns for simplicity (features values are either always the same for ranked games or not useful in our investigation)
ranked_matches_cleaned = ranked_matches.drop(columns=['tag', 'vod', 'date', 'rank', 'type', 'season', 'decayed', 'beginner', 'category', 'gameMode', 'botSource', 'spectators', 'replayExist'])
ranked_matches_cleaned

,id,seed,result,changes,players,seedType,forfeited,timelines,bastionType,completions
40,4547099,"{'id': 'm723dgkr89cqsgkp', 'nether': 'STABLES'...","{'time': 213742, 'uuid': '2ee501c437a14ed5aea3...","[{'uuid': '2ee501c437a14ed5aea3db39da3607db', ...","[{'uuid': '7bafa1944f0e41578b43839800457785', ...",SHIPWRECK,True,"[{'data': None, 'time': 213741, 'type': 'proje...",STABLES,[]
48,4547107,"{'id': 'm7235dgdf4ae2tu8', 'nether': 'BRIDGE',...","{'time': 284255, 'uuid': '8adddd22d4ec469f86ab...","[{'uuid': '8adddd22d4ec469f86ab22c92b98e7c3', ...","[{'uuid': '8adddd22d4ec469f86ab22c92b98e7c3', ...",DESERT_TEMPLE,True,"[{'data': None, 'time': 284255, 'type': 'proje...",BRIDGE,[]
50,4547109,"{'id': 'm723cxvchs0a8eof', 'nether': 'STABLES'...","{'time': 344543, 'uuid': '3372cd1a314a42c9adee...","[{'uuid': '3372cd1a314a42c9adee70d9355c065c', ...","[{'uuid': '3372cd1a314a42c9adee70d9355c065c', ...",VILLAGE,True,"[{'data': None, 'time': 344543, 'type': 'proje...",STABLES,[]
52,4547111,"{'id': 'm722x0y4so7oxpiz', 'nether': 'STABLES'...","{'time': 420457, 'uuid': None}","[{'uuid': '4b3b1306cad440859ade3c77fe15a3ce', ...","[{'uuid': '944a03a48b7e4dada3369c576ed3fb8b', ...",DESERT_TEMPLE,True,"[{'data': None, 'time': 413504, 'type': 'proje...",STABLES,[]
53,4547112,"{'id': 'm7232xdld779myba', 'nether': 'BRIDGE',...","{'time': 286047, 'uuid': 'e9746018a2834f7585d0...","[{'uuid': 'e9746018a2834f7585d0f3467f9e8fc4', ...","[{'uuid': '6da9aa6435e14205a18c9a6dddb7f558', ...",VILLAGE,True,"[{'data': None, 'time': 286046, 'type': 'proje...",BRIDGE,[]
...,...,...,...,...,...,...,...,...,...,...
5049594,9600365,"{'id': 'm722t6f9bmuhh987', 'nether': 'BRIDGE',...","{'time': 588002, 'uuid': '973080614b054d7a9690...","[{'uuid': '973080614b054d7a9690fd83f505f0dd', ...","[{'uuid': '72b7568cec6d42aeb4f33c22afd874a4', ...",RUINED_PORTAL,True,"[{'data': None, 'time': 588002, 'type': 'proje...",BRIDGE,[]
5049595,9600366,"{'id': 'm7235oyqp5kt31sg', 'nether': 'TREASURE...","{'time': 336868, 'uuid': '32971d61ee7146fcb738...","[{'uuid': '32971d61ee7146fcb7385afe09eff042', ...","[{'uuid': 'fd62d46fe1ac4368b18e64249c370f30', ...",DESERT_TEMPLE,True,"[{'data': None, 'time': 336867, 'type': 'proje...",TREASURE,[]
5049596,9600367,"{'id': 'm722uu70d4h4jn6o', 'nether': 'STABLES'...","{'time': 1451288, 'uuid': 'd934441161df475aa20...","[{'uuid': 'd934441161df475aa20fc34eb1b2c1fc', ...","[{'uuid': 'd934441161df475aa20fc34eb1b2c1fc', ...",VILLAGE,False,"[{'data': None, 'time': 1441280, 'type': 'proj...",STABLES,"[{'time': 1451288, 'uuid': 'd934441161df475aa2..."
5049597,9600368,"{'id': 'm722y3jjr6q407k4', 'nether': 'STABLES'...","{'time': 730821, 'uuid': 'c6f20e05d06d4f698cfb...","[{'uuid': 'c6f20e05d06d4f698cfba361636a7024', ...","[{'uuid': '4eea0516cb0c4c528cefe85448cac786', ...",VILLAGE,False,"[{'data': None, 'time': 720732, 'type': 'proje...",STABLES,"[{'time': 730821, 'uuid': 'c6f20e05d06d4f698cf..."
5049598,9600369,"{'id': 'm722yg7k6zonvv6j', 'nether': 'BRIDGE',...","{'time': 1564058, 'uuid': '2e7e7d33a1ff43ed941...","[{'uuid': '2e7e7d33a1ff43ed9413a0ccd9305e2c', ...","[{'uuid': '2e7e7d33a1ff43ed9413a0ccd9305e2c', ...",VILLAGE,False,"[{'data': None, 'time': 1554058, 'type': 'proj...",BRIDGE,"[{'time': 1564058, 'uuid': '2e7e7d33a1ff43ed94..."

In [33]:
ranked_matches_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2995159 entries, 40 to 5049598
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   seed         object
 2   result       object
 3   changes      object
 4   players      object
 5   seedType     object
 6   forfeited    bool
 7   timelines    object
 8   bastionType  object
 9   completions  object
dtypes: bool(1), int64(1), object(8)
memory usage: 231.4+ MB

In [34]:
ranked_matches_cleaned.to_parquet('rankedmatches.parquet')